# Generated by Django 6.0.1 on 2026-02-10 18:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('team', 'Team'), ('public', 'Public')], default='private', max_length=20)),
                ('lab_enabled', models.BooleanField(default=True, help_text='Enable Project Lab for data analysis')),
                ('duckdb_path', models.CharField(blank=True, help_text='Path to DuckDB database file for this project', max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('max_storage_gb', models.FloatField(default=5.0, help_text='Maximum storage in GB for datasets', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100.0)])),
                ('max_compute_hours', models.FloatField(default=10.0, help_text='Maximum compute hours per month', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1000.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('analyst', 'Analyst'), ('contributor', 'Contributor'), ('lead', 'Lead')], default='viewer', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='projects.project')),
            ],
            options={
                'ordering': ['-invited_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='projects.project')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('analyst', 'Analyst'), ('contributor', 'Contributor'), ('lead', 'Lead')], default='viewer', max_length=20)),
                ('can_view_data', models.BooleanField(default=True)),
                ('can_run_analysis', models.BooleanField(default=False)),
                ('can_publish_results', models.BooleanField(default=False)),
                ('can_manage_connectors', models.BooleanField(default=False)),
                ('can_invite_members', models.BooleanField(default=False)),
                ('can_execute_pipelines', models.BooleanField(default=False, help_text='Can run data pipelines in Project Lab')),
                ('can_create_datasets', models.BooleanField(default=False, help_text='Can create new datasets')),
                ('can_manage_data_sources', models.BooleanField(default=False, help_text='Can configure data sources')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', '-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', '-updated_at'], name='projects_pr_workspa_e8b93d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['creator', '-updated_at'], name='projects_pr_creator_b54f6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('workspace', 'slug')},
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['project', 'invitee_email', 'status'], name='projects_pr_project_78b99c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvitation',
            index=models.Index(fields=['invitee', 'status'], name='projects_pr_invitee_5d04a2_idx'),
        ),
        migrations.AddIndex(
            model_name='projectjoinrequest',
            index=models.Index(fields=['project', 'status'], name='projects_pr_project_0d708e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectjoinrequest',
            index=models.Index(fields=['user', 'status'], name='projects_pr_user_id_5bdf9f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectjoinrequest',
            unique_together={('project', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='projectmembership',
            unique_together={('project', 'user')},
        ),
    ]
