# Generated by Django 6.0.1 on 2026-01-26 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(related_name='member_workspaces', through='workspaces.WorkspaceMembership', through_fields=('workspace', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
