# Generated by Django 6.0.1 on 2026-01-26 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_workspacejoinrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workspaceinvitation',
            name='workspaces__invitee_25f936_idx',
        ),
        migrations.RemoveIndex(
            model_name='workspaceinvitation',
            name='workspaces__workspa_bea08e_idx',
        ),
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='invitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_workspace_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_workspace_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='workspaceinvitation',
            index=models.Index(fields=['workspace', 'invitee_email', 'status'], name='workspaces__workspa_37732e_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinvitation',
            index=models.Index(fields=['invitee', 'status'], name='workspaces__invitee_982c63_idx'),
        ),
    ]
