# Generated by Django 6.0.1 on 2026-01-26 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('connector', 'Connector')], max_length=20)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('column_count', models.IntegerField(blank=True, null=True)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(max_length=64)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.dataset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('analysis_type', models.CharField(choices=[('eda', 'Exploratory Data Analysis'), ('stats', 'Statistical Analysis'), ('ml', 'Machine Learning'), ('forecast', 'Forecasting'), ('clustering', 'Clustering'), ('custom', 'Custom')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('parameters', models.JSONField(default=dict)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('result_fingerprint', models.CharField(blank=True, max_length=64)),
                ('environment', models.JSONField(blank=True, default=dict)),
                ('estimated_memory_mb', models.IntegerField(blank=True, null=True)),
                ('actual_memory_mb', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='projects.project')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='analytics.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('clustering', 'Clustering'), ('forecasting', 'Forecasting')], max_length=20)),
                ('algorithm', models.CharField(max_length=100)),
                ('hyperparameters', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('feature_importance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='analytics.analysisrun')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='projects.project')),
                ('training_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trained_models', to='analytics.dataset')),
            ],
        ),
    ]
