# Generated by Django 6.0.1 on 2026-02-10 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.IntegerField()),
                ('resource_name', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('export', 'Export'), ('query', 'Query'), ('share', 'Share')], max_length=50)),
                ('workspace_id', models.IntegerField(blank=True, null=True)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('data_volume', models.BigIntegerField(blank=True, null=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='audit_acces_user_id_685608_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_acces_resourc_2d025d_idx'), models.Index(fields=['workspace_id', '-timestamp'], name='audit_acces_workspa_3f0a8c_idx'), models.Index(fields=['project_id', '-timestamp'], name='audit_acces_project_b6b106_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('action_category', models.CharField(choices=[('auth', 'Authentication'), ('account', 'Account Management'), ('workspace', 'Workspace'), ('project', 'Project'), ('data', 'Data Access'), ('collaboration', 'Collaboration'), ('sync', 'Synchronization'), ('admin', 'Administration')], default='account', max_length=20)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='synced', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx'), models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2a3aef_idx'), models.Index(fields=['action_category', '-timestamp'], name='audit_audit_action__2f407a_idx'), models.Index(fields=['sync_status'], name='audit_audit_sync_st_192984_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('metadata', 'Metadata Sync'), ('projects', 'Project Sync'), ('published', 'Published Artifacts'), ('full', 'Full Sync')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], default='started', max_length=20)),
                ('items_synced', models.IntegerField(default=0)),
                ('items_failed', models.IntegerField(default=0)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', '-started_at'], name='audit_syncl_user_id_345ba8_idx'), models.Index(fields=['status'], name='audit_syncl_status_fd8e14_idx')],
            },
        ),
    ]
